name: Python application

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[test,analyze] --no-cache-dir
    - name: Flake8 lint
      run: |
        pylint src
        pyright src
    - name: Pyright        
      uses: jakebailey/pyright-action@v2.2.1
    - name: Test with pytest
      run: |
        pytest
