name: Python application

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:

jobs:
  build-analysis-test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      env:
        PIP_INDEX_EXTRA_URL: ${{ vars.PIP_INDEX_EXTRA_URL }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[test,analyze] --no-cache-dir --extra-index-url $PIP_INDEX_EXTRA_URL --trusted-host pypi-server      
    - name: Lint (Pylint)
      run: pylint src
    - name: Format check (Black)
      run: black --check src
    - name: Format check (Isort)
      run: isort --check src
    - name: Type check (Pyright)
      run: pyright src
    - name: Security scan (Bandit)
      run: bandit -r src
    - name: Unittests (Pytest)
      run: pytest tests/unittests