name: Tag creation

on:
    push:
        tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
    pypi:
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Update VERSION file
          run: echo "${{  github.ref_name }}" | cut -c 2- > VERSION
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -e '.[build,publish]'  
        - name: Build and publish
          env:
            PIP_USERNAME: ${{ secrets.PIP_USERNAME }}
            PIP_PASSWORD: ${{ secrets.PIP_PASSWORD }}
            PIP_INDEX_EXTRA_URL_REMAINDER: ${{ secrets.PIP_INDEX_EXTRA_URL_REMAINDER }}
            PIP_PROTOCOL: ${{ secrets.PIP_PROTOCOL }}
          run: |
            python -m build
            twine upload --verbose \
              --repository-url $PIP_PROTOCOL://$PIP_INDEX_EXTRA_URL_REMAINDER \
              -u $PIP_USERNAME -p $PIP_PASSWORD dist/*
        - name: Upload dist
          uses: actions/upload-artifact@v2
          with:
            name: dist
            path: dist
    docker:
        needs: pypi
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v2
        - name: Download dist
          uses: actions/download-artifact@v2
          with:
            name: dist
            path: dist
        - name: Update VERSION file
          run: echo "${{  github.ref_name }}" | cut -c 2- > VERSION
        - name: Build docker image
          env:
            DOCKER_HUB_URL: ${{ secrets.DOCKER_HUB_URL }}
            PIP_INDEX_EXTRA_URL_REMAINDER: ${{ secrets.PIP_INDEX_EXTRA_URL_REMAINDER }}
            PIP_INDEX_EXTRA_URL: ${{ secrets.PIP_PROTOCOL }}://${{ secrets.PIP_USERNAME }}:${{ secrets.PIP_PASSWORD }}@${{ secrets.PIP_INDEX_EXTRA_URL_REMAINDER }}
            PACKAGE_NAME: $(ls dist | grep .tar.gz | cut -d '-' -f 1)  
          run: |
            echo $PIP_INDEX_EXTRA_URL > /FILE && \
            docker build -t $DOCKER_HUB_URL/$PACKAGE_NAME:$(cat VERSION) \
             --secret id=PIP_INDEX_EXTRA_URL,env=PIP_INDEX_EXTRA_URL \
             --progress=plain \
             --no-cache \
             --network=host \
             --add-host $PIP_INDEX_EXTRA_URL_REMAINDER:$(dig +short $PIP_INDEX_EXTRA_URL_REMAINDER) \
             .
        - name: Push docker image and cleanup
          env:
            PACKAGE_NAME: $(ls dist | grep .tar.gz | cut -d '-' -f 1)
            DOCKER_HUB_URL: ${{ secrets.DOCKER_HUB_URL }}
            VERSION: $(cat VERSION)
          run: |
            docker push $DOCKER_HUB_URL/$PACKAGE_NAME:$VERSION
            docker rmi $DOCKER_HUB_URL/$PACKAGE_NAME:$VERSION
        