name: Python application

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[test,analyze] --no-cache-dir        
  analyze:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
    - name: Checkout environment from previous job
      uses: actions/checkout@v3
      with:
        ref: ${{ needs.build.outputs.ref }}
    - name: Lint (Pylint)
      run: pylint src
    - name: Format check (Black)
      run: black --check src
    - name: Format check (Isort)
      run: isort --check src
    - name: Type check (Pyright)
      run: pyright src
    - name: Security scan (Bandit)
      run: bandit -r src
  test:
    needs: analyze
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
    - name: Unittests (Pytest)
      run: pytest tests/unittests