name: Tag creation

on:
    push:
        tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
    pypi:
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Update VERSION file
          run: echo "${{  github.ref_name }}" | cut -c 2- > VERSION
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -e '.[build,publish]'
        - name: Build and publish
          env:
            PIP_USERNAME: ${{ secrets.PIP_USERNAME }}
            PIP_PASSWORD: ${{ secrets.PIP_PASSWORD }}
            PIP_INDEX_EXTRA_URL_REMAINDER: ${{ secrets.PIP_INDEX_EXTRA_URL_REMAINDER }}
            PIP_PROTOCOL: ${{ vars.PIP_PROTOCOL }}
          run: |
            python -m build
            twine upload --verbose \
              --repository-url $PIP_PROTOCOL://$PIP_INDEX_EXTRA_URL_REMAINDER \
              -u $PIP_USERNAME -p $PIP_PASSWORD dist/*
    docker:
        needs: pypi
        runs-on: self-hosted
        steps:
        - name: Save package name
          run: echo $(ls dist | grep .tar.gz | cut -d '-' -f 1) > DOCKER_CONTAINER_NAME
        - name: Build docker image
          env:
            DOCKER_HUB_URL: ${{ secrets.DOCKER_HUB_URL }}
            PIP_INDEX_EXTRA_URL_REMAINDER: ${{ secrets.PIP_INDEX_EXTRA_URL_REMAINDER }}
            PIP_INDEX_EXTRA_URL: ${{ vars.PIP_PROTOCOL }}://${{ secrets.PIP_USERNAME }}:${{ secrets.PIP_PASSWORD }}@${{ secrets.PIP_INDEX_EXTRA_URL_REMAINDER }}  
          run: |
            echo $PIP_INDEX_EXTRA_URL > /FILE && \
            docker build -t $DOCKER_HUB_URL/$(cat DOCKER_CONTAINER_NAME):$(cat VERSION) \
             --secret id=PIP_INDEX_EXTRA_URL,env=PIP_INDEX_EXTRA_URL \
             --progress=plain \
             --no-cache \
             --network=host \
             --add-host $PIP_INDEX_EXTRA_URL_REMAINDER:$(dig +short $PIP_INDEX_EXTRA_URL_REMAINDER) \
             .
        - name: Push docker image and cleanup
          env:
            DOCKER_HUB_URL: ${{ secrets.DOCKER_HUB_URL }}
            DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
            DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          run: |
            echo $DOCKER_HUB_PASSWORD | docker login $DOCKER_HUB_URL -u $DOCKER_HUB_USERNAME --password-stdin
            docker push $DOCKER_HUB_URL/$(cat DOCKER_CONTAINER_NAME):$(cat VERSION)
            docker rmi $DOCKER_HUB_URL/$(cat DOCKER_CONTAINER_NAME):$(cat VERSION)
        