on:
    push:
        tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
    pypi:
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Update VERSION file
          run: |
            echo "${{  github.ref_name }}" | cut -c 2- > VERSION
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -e '.[build,publish]'
        - name: Build and publish
          env:
            TWINE_USERNAME: ${{ secrets.TWINE_USERNAME}}
            TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
            PIP_INDEX_EXTRA_URL: ${{ secrets.PIP_INDEX_EXTRA_URL }}
          run: |
            python -m build
            twine upload --verbose --repository-url $PIP_INDEX_EXTRA_URL -u $TWINE_USERNAME -p $TWINE_PASSWORD dist/*
    docker:
        needs: pypi
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v2
        - name: Build docker image
          env:
            DOCKER_HUB_URL: ${{ secrets.DOCKER_HUB_URL }}
            PIP_CONF: ${{ secrets.PIP_CONF_PATH }}
          run: |
            docker build -t ${{ secrets.DOCKER_HUB_URL }}/${{ github.event.repository.name }}:$(cat VERSION) \
             --progress=plain \
             --secret id=PIP_CONF,src=${{ secrets.PIP_CONF_PATH }} \
             --network=host \
             --no-cache \
             .
        - name: Push docker image
          run: |
            docker push ${{ secrets.DOCKER_HUB_URL }}/${{ github.event.repository.name }}:$(cat VERSION)
        - name: Delete docker image
          run: |
            docker rmi ${{ secrets.DOCKER_HUB_URL }}/${{ github.event.repository.name }}:$(cat VERSION)
        