on:
    push:
        tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
    pypi:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Test PyPI server
          run: |
            echo "Checking if PyPI server is running"
            curl -s http://localhost:9291/
        - name: Update VERSION file
          run: |
            echo "${{  github.ref_name }}" | cut -c 2- > VERSION
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -e '.[build,publish]'
        - name: Build and publish
          env:
            TWINE_USERNAME: ${{ secrets.TWINE_USERNAME}}
            TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
            PIP_INDEX_EXTRA_URL: ${{ secrets.PIP_INDEX_EXTRA_URL }}
            PYPI_PORT: ${{ secrets.PYPI_PORT }}
          run: |
            python -m build
            twine upload --repository-url http://127.0.0.1:9291/ -u $TWINE_USERNAME -p $TWINE_PASSWORD dist/*